### PR TITLE
Bumping dependencies, updating test snapshots

### LINKED ISSUE #18: An in-range update of lerna is breaking the build 🚨
## The devDependency [lerna](https://github.com/lerna/lerna) was updated from `3.4.3` to `3.5.0`.

🚨 [View failing branch](https://github.com/zone/frontend/compare/master...zone:greenkeeper%2Flerna-3.5.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

lerna is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push:** The Travis CI build failed ([Details](https://travis-ci.org/zone/frontend/builds/460441257?utm_source=github_status&utm_medium=notification)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 48 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/1c142db1ecb50120f0ddce8ff8a7d9cde1bee278"><code>1c142db</code></a> <code>chore(release): publish v3.5.0</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/fbf962932c15b20567678e33d3be226064d50e59"><code>fbf9629</code></a> <code>refactor(version): Tweak error code when remote branch does not exist</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/b199f328dd9360fe6ffceb318fa92536ebffd5e1"><code>b199f32</code></a> <code>refactor(publish): Allow --git-reset to be configured from lerna.json</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/3b98973e273157ef87b7a1c026cd444ddb824fe3"><code>3b98973</code></a> <code>refactor(publish): Gather current tags filtered by --list glob</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/1aa1712363b07531fbe438639f98642d55ddafa3"><code>1aa1712</code></a> <code>chore: bump eslint-plugin-jest</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/f4edc76a5b04fd92fc0380f4b2d70af74cf666e2"><code>f4edc76</code></a> <code>docs: Remove broken badges</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/bc56839ce5ff5a4a89d8e48c77b24ff472ad438b"><code>bc56839</code></a> <code>chore: sync protocol of public registry</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/1a78f1abaedc4c1058317b0cf5b8c6f40517d6ca"><code>1a78f1a</code></a> <code>chore: reset lockfile</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/3cb7465af13d886ee41cf12ee43f85f5b53e2061"><code>3cb7465</code></a> <code>fix(publish): Ignore non-release tags when detecting <code>from-git</code> (#1782)</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/7ee05d7159023dc1ac77007de5232ed3de0365a3"><code>7ee05d7</code></a> <code>feat(version): Add <code>--include-merged-tags</code> option (#1712)</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/e2c0342c7e5698f6f3d6cd9a81b66eddb838998a"><code>e2c0342</code></a> <code>docs: Fix link to <code>--git-remote</code> option (#1796) [ci skip]</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/eae5619840c385fdebceadfca8f280a515ddd445"><code>eae5619</code></a> <code>feat(publish): Add option <code>--no-git-reset</code> to leave unstaged changes in working tree (#1791)</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/b69a7282b6841f2b40f94e6a7df5ecf565be97a1"><code>b69a728</code></a> <code>feat(run): Log package name and timing in runScriptInPackageCapturing (#1781)</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/9d366543d35d087b9f4af07b98a71eb47da44972"><code>9d36654</code></a> <code>feat(import) Add <code>--dest</code> option to explicitly specify import destination (#1772)</code></li>
<li><a href="https://urls.greenkeeper.io/lerna/lerna/commit/cd34b48203d2b65d8207c127cb736e2e25888295"><code>cd34b48</code></a> <code>fix(version): Add friendly error message when remote branch doesn't exist (#1741)</code></li>
</ul>
<p>There are 48 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/lerna/lerna/compare/aa4ae510b9c0a0935f0b1989859ba873a1e864cc...1c142db1ecb50120f0ddce8ff8a7d9cde1bee278">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by simmo**
FYI: Adds `queueMicrotask` global to all eslint based packages. This is a new browser (+node?) API.

@seaburrows 
Updates browserslist config to include some new browser releases. All good?

@martinherweg @seaburrows 
Our Vue packages has had `eslint-plugin-vue` bumped from `5.0.0-beta.3` > `5.0.0-beta.5`, this brings quite a few changes. From what I can see, there are a lot of log level changes from `error` > `warn`. Can you both take a look? Should we be stricter and manually set some/all of these rules back to error? As a point of reference we are using `plugin:vue/recommended` (strictest) to get the rules with one custom override for `vue/max-attributes-per-line` ([see our config](https://github.com/zone/frontend/blob/master/packages/eslint-config-vue/config.json)).

Fixes #18

### CODE REVIEW

**Comment by simmo** [comment]
Yeah I'm happy to take the lead from you both on this. Feel free to directly edit the PR.

**Comment by sburrows-zone** [comment]
had a look through and agree with the proposed changes. I'd suggest that the 3 you were unsure about @martinherweg should be enabled too.

I've assumed that we're preferencing `shortform` over `longform` as well - please shout if I'm wrong!

@simmo I'd like to keep the vue files looking 'similar-ish' to the react/vanilla ones. From what you can see, do any of the above fly in the face of that?

**Comment by simmo** [comment]
@sburrows-zone Cool, valid point I'll take a look.

**Comment by martinherweg** [comment]
> I've assumed that we're preferencing shortform over longform as well - please shout if I'm wrong!
In which case do you mean ?

I think most of the styles are specific to the template part of vue, how much does the react rules do to formatting of JSX?

**Comment by sburrows-zone** [comment]
> In which case do you mean ?

All cases that have that option.
For example `v-on-style` could mean you must do `v-on:click` or `@click`

**Comment by martinherweg** [comment]
Alright. yeah we should definetly prefer the short form.
I think we are just changing back the level of the message to error, and keep the options themself to default (which is shortform for example)

**Comment by simmo** [comment]
@martinherweg @sburrows-zone I've made the suggested edits to revert the log level for:

- vue/attribute-hyphenation
- vue/html-closing-bracket-spacing
- vue/html-indent
- vue/multiline-html-element-content-newline
- vue/mustache-interpolation-spacing
- vue/no-multi-spaces
- vue/no-spaces-around-equal-signs-in-attribute
- vue/no-template-shadow
- vue/order-in-components
- vue/this-in-template
- vue/v-bind-style
- vue/v-on-style

**Pull request merged**
